import { BookOpen, Printer, Download, FileText } from 'lucide-react';

interface Evidence {
  batesNumber: string;
  description: string;
  date: string;
  type: string;
}

interface BinderProps {
  evidence: Evidence[];
}

export function Binder({ evidence }: BinderProps) {
  const handlePrint = () => {
    const printWindow = window.open('', '', 'width=800,height=600');
    if (!printWindow) return;

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Trial Binder - Table of Contents</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Lato:wght@300;400;600&display=swap');
            
            body {
              font-family: 'Lato', sans-serif;
              padding: 40px;
              color: #1a1a1a;
              line-height: 1.6;
            }
            
            h1 {
              font-family: 'Playfair Display', serif;
              text-align: center;
              border-bottom: 3px solid #B76E79;
              padding-bottom: 20px;
              margin-bottom: 40px;
              font-size: 32px;
            }
            
            .case-info {
              text-align: center;
              margin-bottom: 40px;
              font-size: 14px;
              color: #666;
            }
            
            .toc-entry {
              display: flex;
              justify-content: space-between;
              padding: 12px 0;
              border-bottom: 1px dotted #ccc;
              page-break-inside: avoid;
            }
            
            .toc-entry:hover {
              background: #f9f9f9;
            }
            
            .exhibit-desc {
              flex: 1;
              padding-right: 20px;
            }
            
            .exhibit-bates {
              font-family: monospace;
              font-weight: bold;
              color: #B76E79;
              white-space: nowrap;
            }
            
            .exhibit-date {
              font-size: 12px;
              color: #888;
              margin-left: 20px;
            }
            
            .footer {
              margin-top: 60px;
              padding-top: 20px;
              border-top: 1px solid #ddd;
              text-align: center;
              font-size: 12px;
              color: #888;
            }
            
            @media print {
              body { padding: 20px; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <h1>Trial Binder</h1>
          <div class="case-info">
            <strong>Table of Contents</strong><br>
            Generated: ${new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}<br>
            Total Exhibits: ${evidence.length}
          </div>
          
          <div class="toc-list">
            ${evidence.map((item, index) => `
              <div class="toc-entry">
                <span class="exhibit-desc">
                  <strong>Exhibit ${index + 1}:</strong> ${item.description}
                  <span class="exhibit-date">(${item.date})</span>
                </span>
                <span class="exhibit-bates">${item.batesNumber}</span>
              </div>
            `).join('')}
          </div>
          
          <div class="footer">
            Generated by Litigation Command Center | Privileged & Confidential Attorney Work Product
          </div>
          
          <script>
            window.onload = function() {
              window.print();
            }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
  };

  const handleExportPDF = () => {
    // In a real app, you'd use a library like jsPDF
    alert('PDF export would be implemented here with a library like jsPDF or html2pdf');
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
        <div>
          <h1>The Binder</h1>
          <p className="text-[#36454F]/70 mt-2">Trial exhibit assembly and organization</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={handlePrint}
            className="pill-button gradient-teal text-white flex items-center gap-2 shadow-lg shadow-teal/30"
          >
            <Printer className="w-4 h-4" />
            Print TOC
          </button>
          <button 
            onClick={handleExportPDF}
            className="pill-button bg-white/60 hover:bg-white/80 text-[#36454F] flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            Export PDF
          </button>
        </div>
      </div>

      {/* Binder Preview */}
      <div className="glass-card p-8 md:p-12 bg-white border-2 border-[#E7D8C5]">
        <div className="max-w-4xl mx-auto">
          {/* Cover Page */}
          <div className="text-center mb-12 pb-8 border-b-4 border-[#B76E79]">
            <BookOpen className="w-16 h-16 text-teal mx-auto mb-4" />
            <h2 className="text-4xl mb-4 font-serif">Trial Binder</h2>
            <p className="text-[#36454F]/60">Table of Contents</p>
            <p className="text-sm text-[#36454F]/50 mt-2">
              Generated: {new Date().toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}
            </p>
          </div>

          {/* Table of Contents */}
          {evidence.length === 0 ? (
            <div className="text-center py-12">
              <FileText className="w-16 h-16 text-[#36454F]/20 mx-auto mb-4" />
              <p className="text-[#36454F]/60">No exhibits added yet</p>
              <p className="text-sm text-[#36454F]/50 mt-2">
                Add evidence to your vault to build your trial binder
              </p>
            </div>
          ) : (
            <div className="space-y-1">
              {evidence.map((item, index) => (
                <div 
                  key={item.batesNumber}
                  className="flex items-center justify-between py-4 border-b border-dotted border-[#36454F]/10 hover:bg-[#E1EAE5]/20 px-4 rounded transition-colors"
                >
                  <div className="flex-1 flex items-start gap-4">
                    <span className="text-sm text-[#36454F]/50 font-mono min-w-[60px]">
                      Ex. {index + 1}
                    </span>
                    <div className="flex-1">
                      <p className="text-[#36454F] mb-1">{item.description}</p>
                      <div className="flex gap-4 text-xs text-[#36454F]/50">
                        <span>{item.type}</span>
                        <span>•</span>
                        <span>{item.date}</span>
                      </div>
                    </div>
                  </div>
                  <span className="font-mono text-teal ml-4 whitespace-nowrap">
                    {item.batesNumber}
                  </span>
                </div>
              ))}
            </div>
          )}

          {/* Footer */}
          {evidence.length > 0 && (
            <div className="mt-12 pt-8 border-t border-[#36454F]/10 text-center">
              <p className="text-sm text-[#36454F]/60">
                Total Exhibits: <strong className="text-teal">{evidence.length}</strong>
              </p>
              <p className="text-xs text-[#36454F]/40 mt-4">
                Privileged & Confidential Attorney Work Product
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Tips */}
      <div className="glass-card-teal p-6 border border-teal/30">
        <h3 className="mb-3 text-teal flex items-center gap-2">
          <FileText className="w-5 h-5" />
          Binder Organization Tips
        </h3>
        <ul className="space-y-2 text-sm text-[#36454F]/80">
          <li>• Organize exhibits chronologically or by topic</li>
          <li>• Use Bates numbers for easy reference during trial</li>
          <li>• Create multiple binders: one for you, one for the judge, one for opposing counsel</li>
          <li>• Include tab dividers between major sections</li>
          <li>• Always bring a backup digital copy on your laptop</li>
        </ul>
      </div>
    </div>
  );
}
